// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jbuynmwqoemvqytmiyez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpidXlubXdxb2VtdnF5dG1peWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3OTEzNjQsImV4cCI6MjA4MzM2NzM2NH0.AlytMhFOypfKbGr9FIoMPOrc8LOA5Eja-gUD9ecXTgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);